## MapLoader.gd
## Parses the level_map.json file generated by the 2D web editor and dynamically 
## instances the blocks/enemies at runtime in Godot.
extends Node3D
class_name MapLoader


signal map_loaded(map_data: Array, grid_size: int, cell_size: float, offset: Vector2)

@export var map_json_path: String = "res://scripts/data/raw/level_map.json"
@export var enemy_scene: PackedScene

# IDs matching the JS map_editor
const ID_WALL = 1
const ID_SPAWN = 2
const ID_ENEMY = 3
const ID_TORCH = 4
const ID_TOMBSTONE = 5
const ID_TREE = 6
const ID_CAMPFIRE = 7
const ID_EXIT = 8

var current_map_data: Array = []
var current_grid_size: int = 0
var current_cell_size: float = 2.0
var current_offset: Vector2 = Vector2.ZERO

# ─── Materials ──────────────────────────────────────────────────────────────
var mat_stone  : StandardMaterial3D
var mat_wood   : StandardMaterial3D
var mat_grave  : StandardMaterial3D
var mat_metal  : StandardMaterial3D
var mat_fire   : StandardMaterial3D

func _ready() -> void:
	add_to_group("map_loader")
	_build_materials()
	
	# DIAGNOSTIC: Spawn a giant red cube at origin to see if ANY geometry shows up on client
	if not multiplayer.is_server():
		var diag = MeshInstance3D.new(); var box = BoxMesh.new(); box.size = Vector3(2, 10, 2)
		var m = StandardMaterial3D.new(); m.albedo_color = Color.RED; diag.mesh = box; diag.material_override = m
		diag.position = Vector3(0, 5, 0); add_child(diag)
		print("[MapLoader] Diagnostic cube spawned at origin.")

	if NetworkManager.is_multiplayer_active():
		if multiplayer.is_server():
			_load_map()
		else:
			print("[MapLoader] Client ready. Loading local floor placeholder and requesting sync...")
			_load_map()
			request_map_sync.rpc_id(1)
			
			# Also listen for data sync just in case
			if not NetworkManager.player_data_synced.is_connected(_on_peer_data_received):
				NetworkManager.player_data_synced.connect(_on_peer_data_received)
	else:
		call_deferred("_load_map")

func _on_peer_data_received(id: int, _data: Dictionary) -> void:
	if id == 1: # Server
		_on_initial_sync_ready()

func _on_initial_sync_ready() -> void:
	# Check specifically for a node with 'Level' in its name or that contains geometry
	var has_actual_level = false
	for child in get_children():
		if child.name.contains("Level") or child.name.contains("map") or child.has_node("ProceduralTerrain"):
			has_actual_level = true
			break
			
	if not has_actual_level:
		print("[MapLoader] Initial sync ready, NO LEVEL FOUND. Loading floor: ", PlayerData.dungeon_floor)
		_load_map()
	else:
		print("[MapLoader] Initial sync ready, level already exists. Checking for floor update...")
	
	# Request an update just in case the server floor changed since registration
	request_map_sync.rpc_id(1)


@rpc("any_peer", "call_local", "reliable")
func request_map_sync() -> void:
	if not multiplayer.is_server(): return
	var sender_id = multiplayer.get_remote_sender_id()
	print("[MapLoader] Peer ", sender_id, " requested map sync. Sending Floor: ", PlayerData.dungeon_floor)
	load_map_networked.rpc(PlayerData.dungeon_floor)

@rpc("any_peer", "call_local", "reliable")
func load_map_networked(floor_id: int) -> void:
	var sender_id = multiplayer.get_remote_sender_id()
	if sender_id != 0 and not multiplayer.is_server() and sender_id != 1:
		return
	var has_actual_level = false
	for child in get_children():
		if child.name.contains("Level") or child.name.contains("map") or child.has_node("ProceduralTerrain"):
			has_actual_level = true
			break

	if PlayerData.dungeon_floor != floor_id or not has_actual_level:
		if PlayerData.dungeon_floor != floor_id:
			print("[MapLoader] Floor mismatch (Sync: ", floor_id, " Local: ", PlayerData.dungeon_floor, "). Reloading.")
		else:
			print("[MapLoader] Level missing on client. Loading floor: ", floor_id)
		PlayerData.dungeon_floor = floor_id
		_load_map()
	else:
		print("[MapLoader] Floor sync received, already matches server: ", floor_id)


func _build_materials() -> void:
	mat_stone = StandardMaterial3D.new()
	
	# Load the custom texture if available
	var tex_path = "res://assets/textures/wall.jpeg"
	var tex = load(tex_path)
	
	if not tex and ResourceLoader.exists(tex_path):
		var img = Image.load_from_file(ProjectSettings.globalize_path(tex_path))
		if img:
			tex = ImageTexture.create_from_image(img)

	if tex:
		mat_stone.albedo_texture = tex
		mat_stone.albedo_color = Color(1, 1, 1) # Reset color so texture isn't tinted dark
		mat_stone.uv1_triplanar = true
		mat_stone.uv1_scale = Vector3(0.2, 0.2, 0.2) # Scale so bricks look proportionate
	else:
		mat_stone.albedo_color = Color(0.35, 0.33, 0.38)
		
	mat_stone.roughness = 0.7

	mat_wood = StandardMaterial3D.new()
	mat_wood.albedo_color = Color(0.25, 0.15, 0.1)
	mat_wood.roughness = 0.8

	mat_grave = StandardMaterial3D.new()
	mat_grave.albedo_color = Color(0.4, 0.38, 0.42)
	mat_grave.roughness = 0.8

	mat_metal = StandardMaterial3D.new()
	mat_metal.albedo_color = Color(0.15, 0.15, 0.2)
	mat_metal.metallic = 0.9
	mat_metal.roughness = 0.3

	mat_fire = StandardMaterial3D.new()
	mat_fire.albedo_color = Color(1.0, 0.6, 0.1)
	mat_fire.emission_enabled = true
	mat_fire.emission = Color(1.0, 0.4, 0.0)
	mat_fire.emission_energy_multiplier = 6.0

func _load_map() -> void:
	var floor_id = PlayerData.dungeon_floor
	var path = "res://scenes/maps/level_" + str(floor_id) + ".tscn"
	
	if not ResourceLoader.exists(path):
		if floor_id == 1:
			printerr("[MapLoader] ERROR: Level file missing: ", path)
			_generate_fallback_floor()
			return
		else:
			print("[MapLoader] Floor ", floor_id, " not found. Looping back to level_1.tscn.")
			path = "res://scenes/maps/level_1.tscn"

	print("[MapLoader] Peer ", multiplayer.get_unique_id(), " attempting load of: ", path)

	var scene = load(path) as PackedScene
	if not scene:
		printerr("[MapLoader] ERROR: Failed to load scene: ", path)
		return

	# Clean up previous map geometry
	for child in get_children():
		if child is Node3D and child.name != "EmergencyLight":
			child.queue_free()

	var level_instance = scene.instantiate()
	add_child(level_instance)

	# Emit empty grid data to maintain compatibility with other scripts listening to the signal
	map_loaded.emit([], 0, 0.0, Vector2.ZERO)
	
	# Spawn dynamic entities like enemies based on markers in the scene
	_spawn_scene_entities()

	# Find the designated spawn point in the new scene and teleport the player
	call_deferred("_teleport_to_scene_spawn")

func _spawn_scene_entities() -> void:
	var enemy_spawns = get_tree().get_nodes_in_group("enemy_spawn")
	for m in enemy_spawns:
		if enemy_scene:
			var e = enemy_scene.instantiate()
			add_child(e)
			e.global_position = m.global_position

func _teleport_to_scene_spawn() -> void:
	var terrain = get_tree().get_first_node_in_group("terrain")
	
	# If terrain exists but collision hasn't been built yet, wait for it
	if terrain and not terrain.has_node("TerrainCollision"):
		if terrain.has_signal("terrain_ready"):
			print("[MapLoader] Waiting for terrain collision to be ready...")
			await terrain.terrain_ready
			print("[MapLoader] Terrain ready — teleporting player.")

	var markers = get_tree().get_nodes_in_group("spawn_point")
	var pos = Vector3.ZERO
	
	if markers.size() > 0:
		var sp = markers[0].global_position
		if terrain and terrain.has_method("get_safe_spawn_near"):
			pos = terrain.get_safe_spawn_near(sp.x, sp.z)
			print("[MapLoader] Spawning player at safe terrain pos: ", pos)
		elif terrain and terrain.has_method("get_height_at"):
			var ground_y = terrain.get_height_at(sp.x, sp.z)
			pos = Vector3(sp.x, ground_y + 1.5, sp.z)
		else:
			pos = Vector3(sp.x, sp.y + 1.0, sp.z)
			print("[MapLoader] No terrain found, using marker pos: ", pos)
	
	if pos != Vector3.ZERO:
		_teleport_player(pos)
	else:
		# Last resort — use terrain centre if no spawn point
		if terrain and terrain.has_method("get_safe_spawn_near"):
			pos = terrain.get_safe_spawn_near(0.0, 0.0)
			print("[MapLoader] No spawn marker, using terrain centre: ", pos)
			_teleport_player(pos)


func _add_solid_box(pos: Vector3, size: Vector3, mat: StandardMaterial3D) -> void:
	var mi = MeshInstance3D.new()
	var bm = BoxMesh.new()
	bm.size = size
	mi.mesh = bm
	mi.material_override = mat
	mi.position = pos
	var sb = StaticBody3D.new()
	var cs = CollisionShape3D.new()
	var bs = BoxShape3D.new()
	bs.size = size
	cs.shape = bs
	sb.add_child(cs)
	mi.add_child(sb)
	add_child(mi)

func _add_box_mesh_only(pos: Vector3, size: Vector3, mat: StandardMaterial3D) -> void:
	var mi = MeshInstance3D.new()
	var bm = BoxMesh.new()
	bm.size = size
	mi.mesh = bm
	mi.material_override = mat
	mi.position = pos
	add_child(mi)

func _add_cylinder(pos: Vector3, top_r: float, bot_r: float, h: float, mat: StandardMaterial3D, rot_deg: Vector3) -> void:
	var mi = MeshInstance3D.new()
	var cyl = CylinderMesh.new()
	cyl.top_radius = top_r
	cyl.bottom_radius = bot_r
	cyl.height = h
	mi.mesh = cyl
	mi.material_override = mat
	mi.position = pos
	mi.rotation_degrees = rot_deg
	add_child(mi)

func _teleport_player(pos: Vector3) -> void:
	var players = get_tree().get_nodes_in_group("player")
	for p in players:
		# Only teleport our local player instance
		if p.is_multiplayer_authority():
			if p.has_method("teleport_to"):
				p.teleport_to(pos, 10.0)
			else:
				p.global_position = pos
				p.rotation_degrees.y = 10.0

func _on_exit_entered(body: Node3D) -> void:
	if not body.is_in_group("player"): return
	PlayerData.dungeon_floor += 1
	PlayerData.current_zone = "Dungeon Floor " + str(PlayerData.dungeon_floor)
	_show_transition_animation()

func _show_transition_animation() -> void:
	var hud_nodes = get_tree().get_nodes_in_group("hud")
	var canvas = hud_nodes[0] if hud_nodes.size() > 0 else null
	if not canvas:
		get_tree().reload_current_scene()
		return
		
	var overlay = ColorRect.new()
	overlay.color = Color(0, 0, 0, 0)
	overlay.set_anchors_preset(Control.PRESET_FULL_RECT)
	canvas.add_child(overlay)
	
	var lbl = Label.new()
	lbl.text = "Floor " + str(PlayerData.dungeon_floor - 1) + " Complete"
	lbl.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	lbl.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	lbl.set_anchors_preset(Control.PRESET_FULL_RECT)
	lbl.add_theme_font_size_override("font_size", 64)
	lbl.modulate.a = 0
	canvas.add_child(lbl)
	
	var tween = create_tween()
	tween.tween_property(overlay, "color:a", 1.0, 1.0)
	tween.parallel().tween_property(lbl, "modulate:a", 1.0, 1.0)
	tween.tween_interval(1.0)
	tween.tween_callback(func(): get_tree().reload_current_scene())

func _show_game_over(msg: String) -> void:
	var hud_nodes = get_tree().get_nodes_in_group("hud")
	var canvas = hud_nodes[0] if hud_nodes.size() > 0 else null
	if canvas:
		var lbl = Label.new()
		lbl.text = msg
		lbl.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		lbl.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
		lbl.set_anchors_preset(Control.PRESET_FULL_RECT)
		lbl.add_theme_font_size_override("font_size", 80)
		canvas.add_child(lbl)

func _generate_fallback_floor() -> void:
	# Disabled to prevent ghost geometry conflicts with TerrainGenerator
	pass
